server:
  port: 8888

spring:
  main:
    banner-mode: off

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          searchLocations: "[classpath:/, classpath:/config, classpath:/config/{application}]"

management:
  endpoints:
    web:
      exposure:
        include: "health,refresh"

  health:
    readiness-state:
      enabled: true

    liveness-state:
      enabled: true

  endpoint:
    health:
      probes:
        enabled: true
