FROM python:3

RUN adduser app
USER app
WORKDIR /home/service

COPY ./requirements.txt /home/service/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /home/service/requirements.txt
COPY ./app /home/service/app

EXPOSE 8080
CMD ["python3", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
